"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _blog_card from './blog-card.bones.json'
import _blog_card_featured from './blog-card-featured.bones.json'
import _blog_post from './blog-post.bones.json'

configureBoneyard({"color":"hsl(200 8% 16%)","darkColor":"hsl(200 8% 14%)","animate":"shimmer","shimmerColor":"hsl(168 45% 42% / 0.12)","darkShimmerColor":"hsl(168 45% 42% / 0.18)","speed":"2.2s","stagger":60})

registerBones({
  "blog-card": _blog_card,
  "blog-card-featured": _blog_card_featured,
  "blog-post": _blog_post,
})
